### ISSUE TITLE
Configurator issues.

### ISSUE THREAD

**Issue by Odysseus86** [simon04/gnome-shell-extension-weather#29] opened 2011-11-06 10:16 UTC
- Filling the **Label** field has no effect.
- The _left_ and _right_ options in **Position in Panel** are exchanged (i.e., selecting _left_ makes the notification appear on the right side of the panel and viceversa).
- The checkboxes (**Translate Weather Conditions**, **Symbolic Icons**, **Show text in Panel**, **Show Comment in Panel**) seems to have no effect (e.g., symbolic icons are always displayed, even if I uncheck the related checkbox).

**Comment by simon04** [comment] 2011-11-06 11:24
> Filling the Label field has no effect.

At the moment, changes in text fields must be confirmed by `[Return]`. This could or should probably be changed.

I'm happy to hear some ideas. I wouldn't like to apply the settings on every keypress as this triggers a new request in the extension.

**Comment by ferdnyc** [comment] 2011-11-19 15:21
> At the moment, changes in text fields must be confirmed by [Return]. This could or should probably be changed.
> 
> I'm happy to hear some ideas. I wouldn't like to apply the settings on every keypress as this triggers a new request in the extension.

Well, at least loss-of-input-focus should probably be added to that list. So, if you tab out of the field, your changes are applied. (That doesn't solve the problem if you just close the window with a modified text field un-applied, but it'd help. Mind, you I haven't looked closely at the implementation to see how much control you have over that.)

**Comment by ferdnyc** [comment] 2011-11-19 15:23
Myself, I found having two options "**Show Text in Panel**" & "**Show Comment in Panel**" confusing, especially since their tooltip descriptions make it sound like they do exactly the same thing. I'd suggest, perhaps, changing "**Show Comment in Panel**" to "**Include Condition (Comment)**" and indent it as a sub-option of "**Show Text in Panel**". (It'd be even better if it could gray-out / disable when "**Show Text in Panel**" is turned off, to make the dependent relationship clearer.)

I'd also change the description of "**Show Text in Panel**" so that it doesn't make any reference to "comment". As it reads now, it's:

> Whether to show the weather condition text (aka. comment) together with the temperature in the panel (requires restart of GNOME Shell).

Whereas it should probably say something like:

> Display current temperature in panel. If disabled, only the current condition icon is shown. (Requires restart of GNOME Shell.)

...Making "**Include Condition (Comment)**" a dependent option takes care of explaining its presence, so there's no need to mention it at all in the "**Show Text**..." description. (Which I'd personally even consider changing to "**Show Temperature In Panel**". Like I said, having "**Include Condition**..." as a dependent option, perhaps also with a better-worded description, makes that not-confusing IMHO.)

**Comment by ferdnyc** [comment] 2011-11-19 15:31
Oh, sorry! One last thing. In the current configurator.py, the **Position in Panel** selections are ordered:
- center
- right
- left

Which feels a bit awkward, since it's techically an _out_ of order "order". I don't have a preference for which direction, but I'd think either a left-to-right or right-to-left linear progression would be more natural.

**Comment by simon04** [comment] 2011-11-23 17:43
Thank you for your suggestions! Most of your suggestions are implemented.

The text changes are lost when immediately closing the configurator (w/o focusing any other element).

**Comment by simon04** [comment] 2011-12-29 19:50
I'll close this issue for now …
The `prefs` branch was merged in f5dcafd277c9d14a06fe80d8aa31aee0ff4099f1.

**Closed as completed by simon04** 2011-12-29 19:50 UTC

**Comment by ferdnyc** [comment] 2011-12-29 21:52
And I had meant to say, after I played with the branch changes last week — IMHO the latest version is a noticeable improvement. For normal use the configurator feels pretty clear-cut, and the effects of making changes in it are reassuringly predictable & obvious. Thanks very much!
